/**
 * exportService.js
 * PDF (jsPDF + autotable) and Excel (SheetJS/xlsx) export utilities
 * for VyaparBook — party ledgers, reports, and transaction history.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ── Helpers ──────────────────────────────────────────────────────────────────

const fmtAmt = (n) => {
  const num = Number(n) || 0;
  return `₹${num.toLocaleString('en-IN')}`;
};

const fmtDate = (d) => {
  if (!d) return '—';
  try {
    return new Date(d).toLocaleDateString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric',
    });
  } catch { return d; }
};

const computePending = (deal) => {
  const paid = (deal.payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
  return Math.max(0, Number(deal.total_amount || 0) - paid);
};

const branded = (doc, title, subtitle) => {
  // Green header bar
  doc.setFillColor(22, 163, 74); // green-600
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('VyaparBook', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Aapka Digital Khata', 14, 19);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 210 - 14, 12, { align: 'right' });
  if (subtitle) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 210 - 14, 19, { align: 'right' });
  }
  doc.setTextColor(30, 30, 30);
};

// ── 1. Party Ledger PDF ───────────────────────────────────────────────────────

export const exportPartyLedgerPDF = (party, deals, businessName = 'Your Business') => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const totalBusiness = deals.reduce((s, d) => s + Number(d.total_amount || 0), 0);
  const totalPaid = deals.reduce((s, d) =>
    s + (d.payments || []).reduce((ps, p) => ps + Number(p.amount || 0), 0), 0);
  const totalPending = deals.reduce((s, d) => s + computePending(d), 0);

  // Header
  branded(doc, 'Party Ledger', fmtDate(new Date().toISOString()));

  // Party info box
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(22, 163, 74);
  doc.text(party?.name || 'Party', 14, 38);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  if (party?.type) doc.text(`Type: ${party.type}`, 14, 45);
  if (party?.phone) doc.text(`Phone: ${party.phone}`, 14, 51);
  doc.text(`Generated by: ${businessName}`, 14, 57);

  // Summary box
  const summaryY = 64;
  doc.setFillColor(240, 253, 244); // green-50
  doc.roundedRect(14, summaryY, 182, 22, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  const col = 182 / 3;
  [
    ['Total Business', fmtAmt(totalBusiness)],
    ['Total Paid', fmtAmt(totalPaid)],
    ['Pending', fmtAmt(totalPending)],
  ].forEach(([label, value], i) => {
    const x = 14 + col * i + col / 2;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(label, x, summaryY + 8, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(totalPending > 0 && label === 'Pending' ? 220 : 30, 38 * (label === 'Pending' && totalPending > 0 ? 0 : 1), 38 * (label === 'Pending' && totalPending > 0 ? 0 : 1));
    doc.text(value, x, summaryY + 16, { align: 'center' });
  });
  doc.setTextColor(30, 30, 30);

  // Deals table
  const rows = deals.map((d) => {
    const paid = (d.payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
    const pending = computePending(d);
    return [
      fmtDate(d.deal_date),
      (d.type || '').toUpperCase(),
      (d.commodity || '—').toUpperCase(),
      d.quantity ? `${d.quantity} ${d.unit || ''}` : '—',
      d.rate ? fmtAmt(d.rate) : '—',
      fmtAmt(d.total_amount),
      fmtAmt(paid),
      pending > 0 ? fmtAmt(pending) : '✓ Clear',
    ];
  });

  autoTable(doc, {
    head: [['Date', 'Type', 'Commodity', 'Qty', 'Rate', 'Total', 'Paid', 'Pending']],
    body: rows,
    startY: summaryY + 28,
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 255, 250] },
    columnStyles: {
      5: { fontStyle: 'bold' },
      7: { textColor: [220, 38, 38], fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 7 && data.cell.raw === '✓ Clear') {
        data.cell.styles.textColor = [22, 163, 74];
      }
    },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      `VyaparBook — Page ${i} of ${pageCount} — vyaparbook.vercel.app`,
      105, 290, { align: 'center' }
    );
  }

  doc.save(`${party?.name || 'party'}-ledger-${new Date().toISOString().split('T')[0]}.pdf`);
};

// ── 2. Reports PDF ────────────────────────────────────────────────────────────

export const exportReportPDF = (data, period, businessName = 'Your Business') => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const periodLabel = period === 'month' ? 'This Month'
    : period === 'week' ? 'This Week' : 'All Time';

  branded(doc, `Business Report — ${periodLabel}`, fmtDate(new Date().toISOString()));

  // Summary
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(businessName, 14, 38);

  const summaryY = 44;
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, summaryY, 182, 22, 2, 2, 'F');
  const net = (data?.totalSale || 0) - (data?.totalPurchase || 0);
  [
    ['Purchases', fmtAmt(data?.totalPurchase)],
    ['Sales', fmtAmt(data?.totalSale)],
    [net >= 0 ? 'Net Profit' : 'Net Investment', fmtAmt(Math.abs(net))],
  ].forEach(([label, value], i) => {
    const col = 182 / 3;
    const x = 14 + col * i + col / 2;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(label, x, summaryY + 8, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text(value, x, summaryY + 16, { align: 'center' });
  });
  doc.setTextColor(30, 30, 30);

  // Pending to Pay table
  if (data?.toPay?.length) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('🔴 Pending to Pay', 14, summaryY + 32);
    autoTable(doc, {
      head: [['Party', 'Pending Amount']],
      body: data.toPay.map(p => [p.party_name, fmtAmt(p.total_pending)]),
      startY: summaryY + 36,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [239, 68, 68], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [255, 250, 250] },
    });
  }

  // Pending to Receive table
  const afterPayY = doc.lastAutoTable?.finalY || summaryY + 36;
  if (data?.toReceive?.length) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('🟢 Pending to Receive', 14, afterPayY + 10);
    autoTable(doc, {
      head: [['Party', 'Pending Amount']],
      body: data.toReceive.map(p => [p.party_name, fmtAmt(p.total_pending)]),
      startY: afterPayY + 14,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [240, 253, 244] },
    });
  }

  doc.save(`vyaparbook-report-${period}-${new Date().toISOString().split('T')[0]}.pdf`);
};

// ── 3. All Transactions Excel ─────────────────────────────────────────────────

export const exportTransactionsExcel = (deals, period = 'all') => {
  const rows = (deals || []).map((d) => {
    const paid = (d.payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
    const pending = computePending(d);
    return {
      Date: fmtDate(d.deal_date),
      Party: d.parties?.name || '—',
      Type: (d.type || '').toUpperCase(),
      Commodity: d.commodity || '—',
      Quantity: d.quantity || 0,
      Unit: d.unit || '—',
      'Rate (₹)': Number(d.rate) || 0,
      'Total Amount (₹)': Number(d.total_amount) || 0,
      'Paid (₹)': paid,
      'Pending (₹)': pending,
      Source: d.source || 'pwa',
      'Deal ID': d.id,
    };
  });

  const ws = XLSX.utils.json_to_sheet(rows);

  // Column widths
  ws['!cols'] = [
    { wch: 14 }, { wch: 20 }, { wch: 10 }, { wch: 14 },
    { wch: 10 }, { wch: 8 }, { wch: 12 }, { wch: 16 },
    { wch: 12 }, { wch: 12 }, { wch: 10 }, { wch: 36 },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Transactions');

  // Summary sheet
  const totalBusiness = rows.reduce((s, r) => s + r['Total Amount (₹)'], 0);
  const totalPaid = rows.reduce((s, r) => s + r['Paid (₹)'], 0);
  const totalPending = rows.reduce((s, r) => s + r['Pending (₹)'], 0);
  const summary = [
    { Metric: 'Total Deals', Value: rows.length },
    { Metric: 'Total Business (₹)', Value: totalBusiness },
    { Metric: 'Total Paid (₹)', Value: totalPaid },
    { Metric: 'Total Pending (₹)', Value: totalPending },
    { Metric: 'Exported On', Value: new Date().toLocaleString('en-IN') },
    { Metric: 'Period', Value: period },
  ];
  const wsSummary = XLSX.utils.json_to_sheet(summary);
  wsSummary['!cols'] = [{ wch: 22 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  XLSX.writeFile(wb, `vyaparbook-transactions-${period}-${new Date().toISOString().split('T')[0]}.xlsx`);
};

// ── 4. Party Ledger Excel ─────────────────────────────────────────────────────

export const exportPartyLedgerExcel = (party, deals) => {
  const rows = (deals || []).map((d) => {
    const paid = (d.payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
    return {
      Date: fmtDate(d.deal_date),
      Type: (d.type || '').toUpperCase(),
      Commodity: d.commodity || '—',
      Quantity: d.quantity || 0,
      Unit: d.unit || '—',
      'Rate (₹)': Number(d.rate) || 0,
      'Total (₹)': Number(d.total_amount) || 0,
      'Paid (₹)': paid,
      'Pending (₹)': computePending(d),
    };
  });

  const ws = XLSX.utils.json_to_sheet(rows);
  ws['!cols'] = [
    { wch: 14 }, { wch: 10 }, { wch: 14 }, { wch: 10 },
    { wch: 8 }, { wch: 12 }, { wch: 14 }, { wch: 14 }, { wch: 14 },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, `${party?.name || 'Party'} Ledger`);
  XLSX.writeFile(wb, `${party?.name || 'party'}-ledger-${new Date().toISOString().split('T')[0]}.xlsx`);
};
